stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

default:
  image: docker:latest
  services:
    - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:v$CI_PIPELINE_ID
  K8S_NAMESPACE_DEV: k8s-ns-dev
  K8S_NAMESPACE_PROD: k8s-ns-prod
  # Define the following variables via service
  SERVICE_APP_PATH: .
  SERVICE_NAME: krakend-gateway
  SERVICE_PORT: 8080
  DOCKER_CONTAINER_SERVICE_PORT: 8080
  # Define the following variables in your GitLab project's CI/CD settings
#  SERVER_HOST: $SERVER_HOST
#  SERVER_SSH_USER: $SERVER_SSH_USER
#  SERVER_SSH_PRIVATE_KEY: $SERVER_SSH_PRIVATE_KEY
#  $KUBE_SERVER: $KUBE_SERVER # This is the Kubernetes server URL.
#  $KUBE_TOKEN: $KUBE_TOKEN # This is the Kubernetes token.
#  $DO_API_TOKEN: $DO_API_TOKEN # This is the DigitalOcean API token.

# pipelines based on environment
include:
  - local: "gitlab-manifests/dev/.gitlab-ci.yml"
  - local: "gitlab-manifests/prod/.gitlab-ci.yml"