apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
  annotations:
#    kubernetes.digitalocean.com/load-balancer-id: "00ed97df-2496-4bbd-9ac1-8e694a429f9b"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "false"
#    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
#    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "do-loadbalancer-certificate-id"
#    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  #type: ClusterIP # internal application
  type: LoadBalancer # external connectivity application and production environment, high availability and scalability
  #type: NodePort # external connectivity application
  selector:
    app: ${SERVICE_NAME}
  ports:
    - name: http
      port: ${SERVICE_PORT} # service cluster port
      targetPort: ${DOCKER_CONTAINER_SERVICE_PORT} # application port from dockerfile
      nodePort: ${K8S_SERVICE_HTTP_NODE_PORT}
      protocol: TCP
#    - name: https
#      protocol: TCP
#      port: 443
#      nodePort: ${K8S_SERVICE_HTTPS_NODE_PORT}
#      targetPort: ${DOCKER_CONTAINER_SERVICE_PORT}